### ISSUE TITLE
[FIX ] - ADD OUTPUT TO EXAMPLE MODULE CALL

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/aws-ec2-vm#3]
CHECK HOW AN OUTOUT FROM AN MODULE WILL BE GIVEN OUT WHEN CALLING A MODULE AND IMPLEMENT IN THE README

https://stuttgart-things.github.io/docs/docs/terraform/

**Comment by ankitsharma12-ops** [comment]
module "test-vm" {
  source        = "github.com/stuttgart-things/aws-ec2-vm"
  ami           = "ami-023adaba598e661ac"
  instance_type = "t2.micro"
}

######  Added the output  #########

output "ec2-vm" {
  value = aws_instance.project-iac.public_ip
}

**Comment by patrick-hermann-sva** [comment]
tested? what about readme?

**Comment by ankitsharma12-ops** [comment]
Hi Sir,

The output block has been added in the README.md of the calling module and did the terraform apply and could see the public IP to be displayed at the output:

Outputs:

ec2-vm = [
  "3.69.144.44",
]

Let's go :)

**Comment by patrick-hermann-sva** [comment]
nice work sir!!
