### ISSUE TITLE
[FIX] - FIX ALL THE LINTING ERRORS FROM THE WORKFLOW

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/aws-ec2-vm#4]

**Comment by ankitsharma12-ops** [comment]
Errors fixed, the variable type was not defined, so added "type=string" and ran the workflow.
It was completed, Run no #5

e.g
variable "region" {
  default     = false
  type        = string            ### this was added ###
  description = "AWS region"
}

**Comment by patrick-hermann-sva** [comment]
nice - pipeline green
