### ISSUE TITLE
[FEATURE] - EXTEND TESTSCRIPT FOR SAVING RENDERED TEMPLATE TO FILE 

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/aws-ec2-vm#6]
script should template a main.tf to call the module with some possible/random values for test coverage

VERIFY CURRENT STATE OF SCRIPT

```bash
cd tests
python3 create-module-test.py 
```

CHANGE VALUES FILE + RERUN SCRIPT

```bash
cd tests
# vi values.yaml
```

EXTEND VALUES FOR ALL POSSIBLE VARIABLES FROM MODULE

```bash
cd tests
# vi values.yaml
```

EXTEND SCRIPT FOR:
- CREATE A FOLDER e.g. /tmp/aws-ec2-vm/
- STORING RENDRED TEMPLATE TO A FILE e.g. /tmp/aws-ec2-vm/main.tf

**Comment by shq1kor** [comment]
1. Added the remaining possible variables from calling module except user_data (not sure whether it worked ), will add once the ssh access to machine works (using cloud-init script).
2. Extended the script for folder creation.


working on  the last part to store the rendered template to main.tf    -- in progress

**Comment by shq1kor** [comment]
I have added the code to save the rendered template to a file

and the file is getting created in the specified path as well and the output is similar to what we see on the console
Please review the same and share the feedback :)

**Comment by patrick-hermann-sva** [comment]
@ankitsharma12-ops please 

- [ ] make the path DRY in the script
- [ ] add a args for values file (default should be values.yaml in script dir) (e.g. python3 test/script.py /tmp/values.yaml)
 WORKS: aws-ec2-vm/tests$ python3 create-module-test.py
 WORKS ALSO: aws-ec2-vm$ python3 create-module-test.py tests/values.yaml 
 WORKS ALSO: aws-ec2-vm$ python3 create-module-test.py tmp/ankit.yaml 
- [ ] add s3 backend for your local testing (we need for execution this script inside the pipeline)
- [ ] test creating ec2 with created main file from the script and state in s3 bucket!

**Comment by ankitsharma12-ops** [comment]
- [ ] make the path DRY in the script       - completed and pushed

**Comment by patrick-hermann-sva** [comment]
check updated script sir @ankitsharma12-ops 



```python3
parser = argparse.ArgumentParser()
parser.add_argument('-f', '--values', default='values.yaml')
args = parser.parse_args()
```

# this works
~/projects/bosch/ankit/aws-ec2-vm$ python3 tests/create-module-test.py --values tests/values.yaml

# this also works
~/projects/bosch/ankit/aws-ec2-vm/tests$ python3 create-module-test.py

**Comment by ankitsharma12-ops** [comment]
Hi Patrick,

So just a summery:

- [ ] make the path DRY in the script   -- its done and dusted ( both branches)
----------------------------------------------------------------------------------------------
- [ ] add a args for values file (default should be values.yaml in script dir) (e.g. python3 test/script.py /tmp/values.yaml)

          **BRANCH MAIN**
           
           **piece of code added:**
           
# ADDING DIFFERENT PATH TO GET THE RENDERED TEMPLATE

if len(sys.argv) > 1:
new_output_path = sys.argv[1]
else:
print("Please provide the output path as an argument.")
sys.exit(1)
## new path to be defined as arg at CLI ##
output_path = new_output_path

output_file = open(output_path, "w")
output_file.write(renderedTemplate)
output_file.close()

Approach:

In the script directory

1. shq1kor@BMH2-C-00134:~/aws-ec2-vm/tests$ python3 create-module-test.py   --> works
2. shq1kor@BMH2-C-00134:~/aws-ec2-vm/tests$ python3 create-module-test.py /tmp/ankit.yaml  --> works

with absolute path:

1. shq1kor@BMH2-C-00134:~/aws-ec2-vm$ python3 tests/create-module-test.py  ---> didn't work 

Reason: the script needs the values.yaml as well to read the data(in the same directory)

Observation: my approach won't work, but learnt a new way to use args with python

--------------------------------------------------------------------------------
               **Feature branch**

          **Added code**
parser = argparse.ArgumentParser()
parser.add_argument('-f', '--values', default='values.yaml')
args = parser.parse_args()

Approach:

In same directory:

1. shq1kor@BMH2-C-00134:~/aws-ec2-vm/tests$ python3 create-module-test.py    --> works

with absolute path:
3. shq1kor@BMH2-C-00134:~/aws-ec2-vm$ python3 tests/create-module-test.py --values tests/values.yaml  --> works
4. shq1kor@BMH2-C-00134:~/aws-ec2-vm$ python3 tests/create-module-test.py --values tests/values.yaml /tmp/ankit.yaml  --> didn't work

Reason: Step 3 not sure whether this is part of the requirement or not

Observation: using args parser it becomes easier to run the script with absolute path and the values.yaml but we can't generate the same in /tmp/ankit.yaml

------------------------------------------------------------
Now working on below 

- [ ] add s3 backend for your local testing (we need for execution this script inside the pipeline)   -- tested locally with local and below is the code:

```hcl
# S3 backend config
# main.tf
terraform {
  required_version = ">= 1.5.5"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.34.0"
    }
  }
  backend "s3" {
    bucket                  = "sthings-transaction-streamer-chunk"
    key                     = "terraform.tfstate"
    region                  = "eu-central-1"
    shared_credentials_file = "/home/shq1kor/.aws/credentials"
  }
}

resource "local_file" "all_users" {
  filename = "users.yaml"
  content  = local.all_users
}

locals {
  all_users = templatefile("${path.module}/users.tmpl", {
    "users" = var.users
  })
}
```

below is the statefile available in the existing bucket (sthings-transaction-streamer-chunk)

shq1kor@BMH2-C-00134:~/aws-ec2-vm$ aws s3 ls s3://sthings-transaction-streamer-chunk/terraform.tfstate
2024-03-19 13:16:08       2560 terraform.tfstate

-----------------------------------------------------------------------------
- [ ] test creating ec2 with created main file from the script and state in s3 bucket!  

Tested and created the EC2 with main file (calling module) and the statefile get stored in S3 

```hcl
# calling module with backend
terraform {
  backend "s3" {
    bucket                  = "sthings-transaction-streamer-chunk"
    key                     = "terraform.tfstate"
    region                  = "eu-central-1"
    shared_credentials_file = "/home/shq1kor/.aws/credentials"
  }
}

module "ec2-vm" {
  source          = "/home/shq1kor/aws-ec2-vm"
  region          = "eu-central-1"
  vpc             = "vpc-ec6e8e86"
  ami             = "ami-023adaba598e661ac"
  itype           = "t2.micro"
  subnet          = "subnet-19213454"
  publicip        = true
  key_name        = "id_rsa.pub" ### name of public key ###
  secgroupname    = "IAC-Sec-Group"
  ssh_path        = "/home/shq1kor/.ssh/id_rsa.pub" ### path of public key ###
  package_upgrade = "true"
  package_update  = "true"
  instance_tags   = { Name = "SERVER02", Environment = "QA", OS = "LINUX", MANAGED = "IAC" }
  packages        = ["wget", "whoami", "chmod", "mv", "update-ca-certificates"]
  users           = [{ name = "ankit-1", gecos = "ankit-1 user", groups = "admin, ubuntu", lock_passwd = "true", sudo = "ALL=(ALL) NOPASSWD:ALL", ssh_authorized_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCVPOX0dQu5b+c0K4XM+JyELPGp3b529gLqDYtVflMtnc+kGGfPNeC/8LkaVKvtPBeLCQ7NqEaiHBmn4UpADw827XTBVK+JLsDVUJOIdpx/Ef0K12zkkt2EAMVZqBkV1Xzg48ZE9wZ4UrzKY3eCg5o2frUrEs9K4zKKBgfzv3O9xKChKqqmWJ4x6H46C0d/y87C8LEwtiNwPWjDfc6QzB925FsVaooPkpinpflZ4H7Z6fJmVa3nh2Ui+f6hPs1V+NdIgf3+JbgnouQYvNG5EXPFgllzV+skx+SY+27mIVAmeKGPHLHHzVv8cjV5FsBv/ILVrFUH8YskySpr0OYS9x8+JD6IdQn1OEPngGlSAY47fCWHGEHd5bRFcWXn69pCm7cUV9D0JzT8rxXhXEiu16v+7jl1X0gPQJtRHjhAOfc24SKKdUkYScf6im86KlvC3fdOXp4HntlhLQq8f/PX9JR7VMRSsLgCiCbjz9mAVJxChfV6uAz1Km41D6f7NalpUKs= shq1kor@BMH2-C-00134" }]
}

output "ec2-vm" {
  value = [module.ec2-vm.ec2instance]
}
```

Outputs:

ec2-vm = [
  "35.159.28.174",
]

shq1kor@BMH2-C-00134:~/aws-ec2-vm$ aws s3 ls s3://sthings-transaction-streamer-chunk/terraform.tfstate
2024-03-19 14:22:50       9153 terraform.tfstate

Verified the content by downloading the terraform.tfstate from the bucket to local and verified the created resources and seems good to me

**Comment by patrick-hermann-sva** [comment]
tested - works w/ ssh into the machine + tags are also working sir!
