### ISSUE TITLE
[FIX] - ADD VARIABLE LIST FOR ADDING AS MUCH TAGS AS A USER WANTS BUT REMOVE HARDCODED

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/aws-ec2-vm#8]
remove this ..
 
 tags = {
    Name        = "SERVER01"
    Environment = "DEV"
    OS          = "UBUNTU"
    Managed     = "IAC"
  }

**Comment by ankitsharma12-ops** [comment]
I have added the below: using map(string) in variables.tf

variable "instance_tags" {
  type = map(string)
  default = {
    Name = "SERVER01"
    Environment = "DEV"
    OS = "UBUNTU"
    Managed = "IAC"
  }
}

Was able to call the module and can see the tags getting associated with the created EC2.

**Comment by ankitsharma12-ops** [comment]
Now checking the possibility of overriding these tags from the calling module (may check the option to define the same in the cloud-init yaml as well)

**Comment by ankitsharma12-ops** [comment]
User Defined Tags as variables from calling module
```hcl

# Calling Module
module "ec2-vm" {
  source          = "/home/shq1kor/aws-ec2-vm"
  region          = "eu-central-1"
  vpc             = "vpc-ec6e8e86"
  ami             = "ami-023adaba598e661ac"
  itype           = "t2.micro"
  subnet          = "subnet-19213454"
  publicip        = true
  key_name        = "id_rsa.pub" ### name of public key ###
  secgroupname    = "IAC-Sec-Group"
  ssh_path        = "/home/shq1kor/.ssh/id_rsa.pub" ### path of public key ###
  package_upgrade = "true"
  package_update  = "true"
  instance_tags   = { Name = "SERVER02", Environment = "QA", OS = "LINUX", MANAGED = "IAC" }    ### User defined ###
  packages        = ["wget", "whoami", "chmod", "mv", "update-ca-certificates"]
  users           = [{ name = "ankit-1", gecos = "ankit-1 user", groups = "admin, ubuntu", lock_passwd = "true", sudo = "ALL=(ALL) NOPASSWD:ALL", ssh_authorized_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCVPOX0dQu5b+c0K4XM+JyELPGp3b529gLqDYtVflMtnc+kGGfPNeC/8LkaVKvtPBeLCQ7NqEaiHBmn4UpADw827XTBVK+JLsDVUJOIdpx/Ef0K12zkkt2EAMVZqBkV1Xzg48ZE9wZ4UrzKY3eCg5o2frUrEs9K4zKKBgfzv3O9xKChKqqmWJ4x6H46C0d/y87C8LEwtiNwPWjDfc6QzB925FsVaooPkpinpflZ4H7Z6fJmVa3nh2Ui+f6hPs1V+NdIgf3+JbgnouQYvNG5EXPFgllzV+skx+SY+27mIVAmeKGPHLHHzVv8cjV5FsBv/ILVrFUH8YskySpr0OYS9x8+JD6IdQn1OEPngGlSAY47fCWHGEHd5bRFcWXn69pCm7cUV9D0JzT8rxXhXEiu16v+7jl1X0gPQJtRHjhAOfc24SKKdUkYScf6im86KlvC3fdOXp4HntlhLQq8f/PX9JR7VMRSsLgCiCbjz9mAVJxChfV6uAz1Km41D6f7NalpUKs= shq1kor@BMH2-C-00134" }]
}

output "ec2-vm" {
  value = [module.ec2-vm.ec2instance]
}
```

same has been pushed to our feature branch as well

**Comment by patrick-hermann-sva** [comment]
looks good! BUUUT var instance_tags should have no default value.. can you remove/male it empty?

**Comment by ankitsharma12-ops** [comment]
Yes Sir,

Its done and now looks like this:

variable "instance_tags" {
  type = map(string)
  default = {}
  description = "To define the tags for resources"
}

and with this, the user can define the variables from the calling module to associate with the EC2 he wants to provision

**Comment by patrick-hermann-sva** [comment]
works sir!
